from xbmcswift2 import Plugin
import xbmc
import os, sys, subprocess
from subprocess import Popen
import json
import re

plugin = Plugin()

games = [["10-Yard Fight (World, set 1)", "10yard"], 
["1942 (Revision B)", "1942"], 
["1943: The Battle of Midway (Euro)", "1943"], 
["1943 Kai: Midway Kaisen (Japan)", "1943kai"], 
["Three Ds - Three Dealers Casino House", "3ds"], 
["The Three Stooges In Brides Is Brides", "3stooges"], 
["4-D Warriors (315-5162)", "4dwarrio"], 
["720 Degrees (rev 4)", "720"], 
["7 e Mezzo", "7mezzo"], 
["'88 Games", "88games"], 
["Eight Ball Action (DK conversion)", "8ballact"], 
["All American Football (rev E)", "aafb"], 
["Atari Baseball (set 1)", "abaseb"], 
["Abunai Houkago - Mou Matenai (Japan 890325)", "abunai"], 
["After Burner II", "aburner2"], 
["Act-Fancer Cybernetick Hyper Weapon (World revision 2)", "actfancr"], 
["Action Fighter (FD1089A 317-0018)", "afighter"], 
["Airwolf", "airwolf"], 
["Ajax", "ajax"], 
["Alcon (US)", "alcon"], 
["Alex Kidd: The Lost Stars (set 2, unprotected)", "alexkidd"], 
["Alien Arena", "alienar"], 
["Alien Sector", "aliensec"], 
["Alien Syndrome (set 4, System 16B, unprotected)", "aliensyn"], 
["Alley Master", "alleymas"], 
["Alpine Ski (set 1)", "alpine"], 
["Altered Beast (set 8, 8751 317-0078)", "altbeast"], 
["Soldier Girl Amazon", "amazon"], 
["Ambush", "ambush"], 
["AmeriDarts (set 1)", "amerdart"], 
["Amidar", "amidar"], 
["American Speedway (set 1)", "amspdwy"], 
["Angel Kids (Japan)", "angelkds"], 
["Anteater", "anteater"], 
["APB - All Points Bulletin (rev 7)", "apb"], 
["Apparel Night (Japan 860929)", "apparel"], 
["Appoooh", "appoooh"], 
["SportTime Table Hockey (Arcadia, set 1, V 2.1)", "ar_airh"], 
["SportTime Bowling (Arcadia, V 2.1)", "ar_bowl"], 
["World Darts (Arcadia, set 1, V 2.1)", "ar_dart"], 
["Magic Johnson's Fast Break (Arcadia, V 2.8)", "ar_fast"], 
["Leader Board (Arcadia, set 1, V 2.4?)", "ar_ldrb"], 
["Ninja Mission (Arcadia, set 1, V 2.5)", "ar_ninj"], 
["RoadWars (Arcadia, V 2.3)", "ar_rdwr"], 
["Sidewinder (Arcadia, set 1, V 2.1)", "ar_sdwr"], 
["World Trophy Soccer (Arcadia, V 3.0)", "ar_socc"], 
["Space Ranger (Arcadia, V 2.0)", "ar_sprg"], 
["Xenon (Arcadia, V 2.3)", "ar_xeon"], 
["Arabian", "arabian"], 
["Arbalester", "arbalest"], 
["Arch Rivals (rev 4.0 6/29/89)", "archrivl"], 
["Argus (Gottlieb, prototype)", "argusg"], 
["Arkanoid (World)", "arkanoid"], 
["Ark Area", "arkarea"], 
["Arkanoid - Revenge of DOH (World)", "arknoid2"], 
["Armed Formation", "armedf"], 
["Armored Car (set 1)", "armorcar"], 
["Arm Wrestling", "armwrest"], 
["ASO - Armored Scrum Object", "aso"], 
["Assault", "assault"], 
["Asteroids Deluxe (rev 3)", "astdelux"], 
["Asteroids (rev 4)", "asteroid"], 
["The Astyanax", "astyanax"], 
["Asuka & Asuka (World)", "asuka"], 
["Atari Football (revision 2)", "atarifb"], 
["Tetris (set 1)", "atetris"], 
["Athena", "athena"], 
["Battle of Atlantis (set 1)", "atlantis"], 
["Attack Ufo", "attckufo"], 
["Avalanche", "avalnche"], 
["Avengers (US set 1)", "avengers"], 
["Aztarac", "aztarac"], 
["Azurian Attack", "azurian"], 
["Back Fire (Tecmo, bootleg)", "backfirt"], 
["Bad Dudes vs. Dragonninja (US)", "baddudes"], 
["Bad Lands", "badlands"], 
["Bagman", "bagman"], 
["Bakutotsu Kijuutei", "bakutotu"], 
["Vs. Balloon Fight (set BF4 A-3)", "balonfgt"], 
["Baluba-louk no Densetsu (Japan)", "baluba"], 
["Mahjong Banana Dream [BET] (Japan 891124)", "bananadr"], 
["Bank Panic", "bankp"], 
["Baseball: The Season II", "basebal2"], 
["Battle Lane! Vol. 5 (set 1)", "battlane"], 
["Battlantis (program code G)", "battlnts"], 
["Bay Route (set 3, World, FD1094 317-0116)", "bayroute"], 
["Bigfoot Bonkers", "bbonk"], 
["Battle Chopper", "bchopper"], 
["Battle Cruiser M-12", "bcruzm12"], 
["Beraboh Man (Japan version C)", "berabohm"], 
["Bermuda Triangle (World?)", "bermudat"], 
["Berzerk (set 1)", "berzerk"], 
["Big 10", "big10"], 
["Big Apple Games (2131-13)", "bigappg"], 
["Big Bucks", "bigbucks"], 
["Big Event Golf (US)", "bigevglf"], 
["The Big Pro Wrestling!", "bigprowr"], 
["Bijokko Gakuen (Japan 880116)", "bijokkog"], 
["Bijokko Yume Monogatari (Japan 870925)", "bijokkoy"], 
["Bikkuri Card (Japan)", "bikkuric"], 
["Bio Attack", "bioatack"], 
["Bionic Commando (Euro)", "bionicc"], 
["Birdiy", "birdiy"], 
["Birdie King", "bking"], 
["Birdie King 2", "bking2"], 
["Birdie King 3", "bking3"], 
["Blades of Steel (version T)", "bladestl"], 
["Blasted", "blasted"], 
["Blaster", "blaster"], 
["Blast Off (Japan)", "blastoff"], 
["Blazer (Japan)", "blazer"], 
["Black Hole", "blkhole"], 
["Black Panther", "blkpnthr"], 
["Black Tiger", "blktiger"], 
["Block Gal (MC-8123B, 317-0029)", "blockgal"], 
["Block Hole", "blockhl"], 
["Block Out (set 1)", "blockout"], 
["Bloxeed (Japan, FD1094 317-0139)", "bloxeed"], 
["Blasteroids (rev 4)", "blstroid"], 
["Blue Print (Midway)", "blueprnt"], 
["Vs. Raid on Bungeling Bay (RD4-2 B)", "bnglngby"], 
["Body Slam (8751 317-0015)", "bodyslam"], 
["Boggy '84", "boggy84"], 
["Bomb Bee", "bombbee"], 
["Bomb Jack (set 1)", "bombjack"], 
["Bongo", "bongo"], 
["Bonze Adventure (World, Newer)", "bonzeadv"], 
["Boomer Rang'r / Genesis (set 1)", "boomrang"], 
["Boot Hill", "boothill"], 
["Botanic", "botanic"], 
["Bottom of the Ninth (version T)", "bottom9"], 
["The Bounty", "bounty"], 
["Bradley Trainer", "bradley"], 
["Brain", "brain"], 
["Brasil 86", "brasil86"], 
["Brasil 87", "brasil87"], 
["Brasil 89 (set 1)", "brasil89"], 
["Break Thru (US)", "brkthru"], 
["Burnin' Rubber", "brubber"], 
["Basketball", "bsktball"], 
["Burger Time (Data East set 1)", "btime"], 
["Vs. Battle City", "btlecity"], 
["Bubbles", "bubbles"], 
["Bubble Bobble", "bublbobl"], 
["Buccaneers (set 1)", "buccanrs"], 
["Buggy Boy/Speed Buggy (cockpit)", "buggyboy"], 
["Bullet (FD1094 317-0041)", "bullet"], 
["Bullfight (315-5065)", "bullfgt"], 
["Burning Force (Japan new version)", "burnforc"], 
["Boardwalk Casino", "bwcasino"], 
["Black Widow", "bwidow"], 
["B-Wings (Japan new Ver.)", "bwings"], 
["Battle Zone (rev 2)", "bzone"], 
["Cabal (World, Joystick version)", "cabal"], 
["Cadash (World)", "cadash"], 
["Caliber 50", "calibr50"], 
["Calipso", "calipso"], 
["Calorie Kun vs Moguranian", "calorie"], 
["Cameltry (US, YM2610)", "cameltry"], 
["Canvas Croquis", "canvas"], 
["Canyon Bomber", "canyon"], 
["Capcom Bowling (set 1)", "capbowl"], 
["Casino Five", "casino5"], 
["Astro Fantasia (DECO Cassette)", "castfant"], 
["Cavelon", "cavelon"], 
["Cosmic Avenger", "cavenger"], 
["Capcom Baseball (Japan)", "cbasebal"], 
["Boulder Dash (DECO Cassette)", "cbdash"], 
["Burger Time (DECO Cassette)", "cbtime"], 
["Burnin' Rubber (DECO Cassette, set 1)", "cburnrub"], 
["Chinese Casino [BET] (Japan)", "ccasino"], 
["Crystal Castles (version 4)", "ccastles"], 
["Cosmic Chasm (set 1)", "cchasm"], 
["Crazy Climber (US)", "cclimber"], 
["Crazy Climber 2 (Japan)", "cclimbr2"], 
["Disco No.1 (DECO Cassette)", "cdiscon1"], 
["DS Telejan (DECO Cassette, Japan)", "cdsteljn"], 
["Centipede (revision 3)", "centiped"], 
["Cerberus", "cerberus"], 
["Fighting Ice Hockey (DECO Cassette)", "cfghtice"], 
["Fishing (DECO Cassette)", "cfishing"], 
["Flying Ball (DECO Cassette)", "cflyball"], 
["Cluster Buster / Graplop (DECO Cassette, set 1)", "cgraplop"], 
["Chack'n Pop", "chaknpop"], 
["Challenger", "challeng"], 
["Chameleon", "chameleo"], 
["Champion Base Ball", "champbas"], 
["Champion Base Ball Part-2: Pair Play (set 1)", "champbb2"], 
["Championship Bowling", "champbwl"], 
["Chanbara", "chanbara"], 
["Change Lanes", "changela"], 
["Changes", "changes"], 
["Champion Boxing", "chboxing"], 
["Check Man", "checkman"], 
["Chelnov - Atomic Runner (World)", "chelnov"], 
["Cheyenne (version 1.0)", "cheyenne"], 
["Chiller (version 3.0)", "chiller"], 
["China Gate (US)", "chinagat"], 
["Chinese Hero", "chinhero"], 
["Ganbare Chinsan Ooshoubu (MC-8123A, 317-5012)", "chinsan"], 
["Choplifter (8751 315-5151)", "choplift"], 
["Chopper I (US set 1)", "chopper"], 
["Chuka Taisen (World)", "chukatai"], 
["Champion Pro Wrestling", "chwrestl"], 
["Highway Chase (DECO Cassette)", "chwy"], 
["Circus Charlie (level select, set 1)", "circusc"], 
["City Bomber (World)", "citybomb"], 
["City Connection (set 1)", "citycon"], 
["City Love (Japan 860908)", "citylove"], 
["Crazy Kong", "ckong"], 
["Crazy Kong Part II (set 1)", "ckongpt2"], 
["Rootin' Tootin' / La-Pa-Pa (DECO Cassette)", "clapapa"], 
["Clay Pigeon (version 2.0)", "claypign"], 
["Cliff Hanger (set 1)", "cliffhgr"], 
["Cloak & Dagger (rev 5)", "cloak"], 
["Lock'n'Chase (DECO Cassette)", "clocknch"], 
["Cloud 9 (prototype)", "cloud9"], 
["Clash-Road", "clshroad"], 
["Lucky Poker (DECO Cassette)", "cluckypo"], 
["Vs. Clu Clu Land", "cluclu"], 
["Mission-X (DECO Cassette)", "cmissnx"], 
["Cherry Master (Corsica, ver.8.01)", "cmv801"], 
["Night Star (DECO Cassette, set 1)", "cnightst"], 
["Country Girl (Japan set 1)", "cntrygrl"], 
["Cobra-Command (World revision 5)", "cobracom"], 
["Colony 7 (set 1)", "colony7"], 
["Combat (version 3.0)", "combat"], 
["Combat School (joystick)", "combatsc"], 
["Combat Hawk", "combh"], 
["Cal Omega - Game 7.4 (Gaming Poker, W.Export)", "comg074"], 
["Cal Omega - Game 7.6 (Arcade Poker)", "comg076"], 
["Cal Omega - Game 8.0 (Arcade Black Jack)", "comg080"], 
["Cal Omega - Game 12.8 (Arcade Game)", "comg128"], 
["Cal Omega - Game 17.51 (Gaming Draw Poker)", "comg175"], 
["Cal Omega - Game 23.9 (Gaming Draw Poker)", "comg239"], 
["Cal Omega - Game 24.0 (Gaming Draw Poker, hold)", "comg240"], 
["Commando (World)", "commando"], 
["Competition Golf Final Round (revision 3)", "compgolf"], 
["Complex X", "complexx"], 
["Contra (US, set 1)", "contra"], 
["Oozumou - The Grand Sumo (DECO Cassette, Japan)", "coozumou"], 
["Cop 01 (set 1)", "cop01"], 
["Country Club", "countryc"], 
["Peter Pepper's Ice Cream Factory (DECO Cassette, set 1)", "cppicf"], 
["Pro Bowling (DECO Cassette)", "cprobowl"], 
["Tournament Pro Golf (DECO Cassette)", "cprogolf"], 
["Pro Soccer (DECO Cassette)", "cpsoccer"], 
["Pro Tennis (DECO Cassette)", "cptennis"], 
["Crackshot (version 2.0)", "cracksht"], 
["Crater Raider", "crater"], 
["Crowns Golf (834-5419-04)", "crgolf"], 
["Crowns Golf in Hawaii", "crgolfhi"], 
["Crime City (World)", "crimec"], 
["Crime Fighters (US 4 players)", "crimfght"], 
["Crossbow (version 2.0)", "crossbow"], 
["Crush Roller (set 1)", "crush"], 
["Crystal Gal 2 (Japan 860620)", "crystal2"], 
["Crystal Gal (Japan 860512)", "crystalg"], 
["Scrum Try (DECO Cassette, set 1)", "cscrtry"], 
["Chicken Shift", "cshift"], 
["Captain Silver (World)", "csilver"], 
["Champion Skill (with Ability)", "csk227it"], 
["Skater (DECO Cassette, Japan)", "cskater"], 
["Championship Sprint (rev 3)", "csprint"], 
["Vs. Castlevania", "cstlevna"], 
["Super Astro Fighter (DECO Cassette)", "csuperas"], 
["Terranean (DECO Cassette)", "cterrani"], 
["Treasure Island (DECO Cassette, set 1)", "ctisland"], 
["Tornado (DECO Cassette)", "ctornado"], 
["Test Tape (DECO Cassette)", "ctsttape"], 
["Cube Quest (01/04/84)", "cubeqst"], 
["Cue Brick (World version D)", "cuebrick"], 
["Curve Ball", "curvebal"], 
["Cutie Q", "cutieq"], 
["Capcom World (Japan)", "cworld"], 
["Cyberball (rev 4)", "cyberbal"], 
["Zeroize (DECO Cassette)", "czeroize"], 
["Daisyarin [BET] (Japan)", "daisyari"], 
["DakkoChan House (MC-8123B, 317-5014)", "dakkochn"], 
["Dambusters (US, set 1)", "dambustr"], 
["Ufo Robo Dangar (12/1/1986)", "dangar"], 
["Danger Zone", "dangerz"], 
["Dangerous Seed (Japan)", "dangseed"], 
["Darius (World)", "darius"], 
["Darius II (triple screen) (Japan)", "darius2"], 
["Dark Planet", "darkplnt"], 
["Darwin 4078 (Japan)", "darwin"], 
["Super Baseball Double Play Home Run Derby", "dblplay"], 
["Dragon Breed (M81 PCB version)", "dbreed"], 
["Double Dragon (Japan)", "ddragon"], 
["Double Dragon II - The Revenge (World)", "ddragon2"], 
["Double Dribble", "ddribble"], 
["Dynamite Dux (set 2, FD1094 317-0096)", "ddux"], 
["Dead Angle", "deadang"], 
["Dead Eye", "deadeye"], 
["Defender (Red label)", "defender"], 
["Demolition Derby", "demoderb"], 
["Demon", "demon"], 
["Devil Fish", "devilfsh"], 
["Devil World", "devilw"], 
["Devastators (ver. Z)", "devstors"], 
["Diamond Run", "diamond"], 
["Dig Dug (rev 2)", "digdug"], 
["Dig Dug II (New Ver.)", "digdug2"], 
["Dingo", "dingo"], 
["Dirt Fox (Japan)", "dirtfoxj"], 
["Disco No.1", "disco"], 
["DJ Boy (set 1)", "djboy"], 
["Donkey Kong (US set 1)", "dkong"], 
["Donkey Kong 3 (US)", "dkong3"], 
["Donkey Kong Junior (US)", "dkongjr"], 
["Mr. Do's Castle (set 1)", "docastle"], 
["Dock Man", "dockman"], 
["Dodgem", "dodgem"], 
["Acrobatic Dog-Fight", "dogfgt"], 
["Dokaben (Japan)", "dokaben"], 
["Doki Doki Penguin Land", "dokidoki"], 
["Domino Man", "domino"], 
["Dominos", "dominos"], 
["Dommy", "dommy"], 
["Don Den Mahjong [BET] (Japan)", "dondenmj"], 
["Don Doko Don (World)", "dondokod"], 
["Dorodon (set 1)", "dorodon"], 
["Do! Run Run (set 1)", "dorunrun"], 
["Discs of Tron (Upright)", "dotron"], 
["Mr. Do's Wild Ride", "dowild"], 
["DownTown / Mokugeki (set 1)", "downtown"], 
["Double Play", "dplay"], 
["Drag Race", "dragrace"], 
["Drakton (DK conversion)", "drakton"], 
["Dream Shopper", "dremshpr"], 
["Dragon Buster", "drgnbstr"], 
["Dragon Unit / Castle of Dragon", "drgnunit"], 
["Dragon Punch (Japan)", "drgpunch"], 
["Driving Force (Pac-Man conversion)", "drivfrcp"], 
["Dr. Micro", "drmicro"], 
["Dr. Toppel's Adventure (World)", "drtoppel"], 
["Dragon Spirit (new version)", "dspirit"], 
["Deluxe Trivia ? Whiz (Edition 5)", "dtrvwz5"], 
["Vs. Duck Hunt (set DH3 E)", "duckhunt"], 
["Dunk Shot (FD1089A 317-0022)", "dunkshot"], 
["Dyger (Korea set 1)", "dyger"], 
["Dynamic Ski", "dynamski"], 
["Dynamite Duke (Europe set 1)", "dynduke"], 
["Dynasty Wars (USA, B-Board 89624B-?)", "dynwar"], 
["Extra Bases", "ebases"], 
["Extra Inning", "einning"], 
["The Electric Yo-Yo (set 1)", "elecyoyo"], 
["Elevator Action", "elevator"], 
["El Grande - 5 Card Draw (New)", "elgrande"], 
["Empire City: 1931 (bootleg?)", "empcity"], 
["Enduro Racer (YM2151, FD1089B 317-0013A)", "enduror"], 
["Enigma II", "enigma2"], 
["Escape from the Planet of the Robot Monsters (set 1)", "eprom"], 
["The Empire Strikes Back", "esb"], 
["Espial (Europe)", "espial"], 
["E-Swat - Cyber Police (set 3, World, FD1094 317-0130)", "eswat"], 
["Vs. Excitebike (set EB4-4 A)", "excitebk"], 
["Excite League (FD1094 317-0079)", "exctleag"], 
["Exciting Soccer II", "exctscc2"], 
["Exciting Soccer", "exctsccr"], 
["Exed Exes", "exedexes"], 
["Exerion", "exerion"], 
["Express Raider (US set 1)", "exprraid"], 
["Exterminator", "exterm"], 
["Extermination (World)", "extrmatn"], 
["Exzisus (Japan, dedicated)", "exzisus"], 
["Eyes (US set 1)", "eyes"], 
["F-1 Dream", "f1dream"], 
["Face Off (Japan)", "faceoff"], 
["Fantastic", "fantastc"], 
["Fantasy Zone II - The Tears of Opa-Opa (MC-8123, 317-0057)", "fantzn2"], 
["Fantasy Zone (Rev A, unprotected)", "fantzone"], 
["FAX", "fax"], 
["Final Fight (World, set 1)", "ffight"], 
["Fighting Basketball", "fghtbskt"], 
["Fighting Hawk (World)", "fhawk"], 
["Field Day", "fieldday"], 
["Final Blow (World)", "finalb"], 
["Finest Hour (Japan)", "finehour"], 
["Firebeast (prototype)", "firebeas"], 
["Fire Fox (set 1)", "firefox"], 
["Fire Trap (US)", "firetrap"], 
["Fire Truck / Smokey Joe", "firetrk"], 
["Fighting Golf (World?)", "fitegolf"], 
["Flashgal (set 1)", "flashgal"], 
["Flicky (128k Version, System 2, 315-5051)", "flicky"], 
["Fly-Boy", "flyboy"], 
["Funky Fish", "fnkyfish"], 
["Food Fight (rev 3)", "foodf"], 
["Forgotten Worlds (World)", "forgottn"], 
["Flash Point (set 2, Japan, FD1094 317-0127A)", "fpoint"], 
["Free Kick (NS6201-A 1987.10)", "freekick"], 
["Freeze", "freeze"], 
["Frenzy", "frenzy"], 
["Frisky Tom (set 1)", "friskyt"], 
["Frogger", "frogger"], 
["Front Line", "frontlin"], 
["The Final Round (version M)", "fround"], 
["Flying Shark (World)", "fshark"], 
["Fighting Soccer (version 4)", "fsoccer"], 
["Frog & Spiders (bootleg?)", "fspiderb"], 
["Status Fun Casino (V1.3s)", "funcsino"], 
["Funky Bee", "funkybee"], 
["Fun World Quiz (Austrian)", "funquiz"], 
["Galaga '88", "galaga88"], 
["Galaxian (Namco set 1)", "galaxian"], 
["Galaxy Game", "galgame"], 
["Cosmo Police Galivan (12/26/1985)", "galivan"], 
["Mahjong Gal no Kaika (Japan)", "galkaika"], 
["Mahjong Gal no Kokuhaku (Japan)", "galkoku"], 
["Gang Wars", "gangwars"], 
["Gardia (317-0006)", "gardia"], 
["Garyo Retsuden (Japan)", "garyoret"], 
["Gauntlet II", "gaunt2"], 
["Gauntlet (rev 14)", "gauntlet"], 
["Green Beret", "gberet"], 
["Gang Busters (set 1)", "gbusters"], 
["Gee Bee (Japan)", "geebee"], 
["Mahjong Gekisha", "gekisha"], 
["Gemini Wing (Japan)", "gemini"], 
["Genie", "genie"], 
["Genpei ToumaDen", "genpeitd"], 
["Guardian (US)", "getstar"], 
["Galaxy Force 2", "gforce2"], 
["Goalie Ghost", "gghost"], 
["Gain Ground (World, 3 Players, Floppy Based, FD1094 317-0058-03d Rev A)", "gground"], 
["The Real Ghostbusters (US 2 Players, revision 2)", "ghostb"], 
["Ghouls'n Ghosts (World)", "ghouls"], 
["Gigandes", "gigandes"], 
["Gigas Mark II (bootleg)", "gigasm2b"], 
["Gimme A Break (7/7/85)", "gimeabrk"], 
["Ginga NinkyouDen (set 1)", "ginganin"], 
["Gionbana (Japan 890120)", "gionbana"], 
["Gladiator (US)", "gladiatr"], 
["Golden Arrow (Standard G8-03)", "gldarrow"], 
["Golden Poker (8VXEC037, NSW)", "gldnpkr"], 
["Ghostmuncher Galaxian (bootleg)", "gmgalax"], 
["Ghosts'n Goblins (World? set 1)", "gng"], 
["Gold Medalist (set 1)", "goldmedl"], 
["Golden Axe (set 6, US, 8751 317-123A)", "goldnaxe"], 
["Golden Poker Double Up (Big Boy)", "goldnpkr"], 
["Gomoku Narabe Renju", "gomoku"], 
["Gondomania (US)", "gondo"], 
["Vs. The Goonies (set E)", "goonies"], 
["Gradius III (World, program code R)", "gradius3"], 
["Gravitar (version 3)", "gravitar"], 
["Gridiron Fight", "gridiron"], 
["Grudge Match (Yankee Game Technology)", "grmatch"], 
["Grobda (New Ver.)", "grobda"], 
["Grudge Match (prototype)", "grudge"], 
["Great Swordsman (World?)", "gsword"], 
["Gone Troppo (1VXEC542, NSW)", "gtroppo"], 
["Give us a Break (3rd edition)", "guab"], 
["Gun.Smoke (World)", "gunsmoke"], 
["Guts n' Glory (prototype)", "guts"], 
["Guzzler", "guzzler"], 
["Guerrilla War (US)", "gwar"], 
["Galactic Warriors", "gwarrior"], 
["Gyrodine", "gyrodine"], 
["Gyruss", "gyruss"], 
["Hachoo!", "hachoo"], 
["HAL21", "hal21"], 
["Hana Awase", "hanaawas"], 
["Mahjong Hana no Momoko gumi (Japan 881201)", "hanamomo"], 
["Hangman", "hangman"], 
["Hang-On (Rev A)", "hangon"], 
["Hang-On Jr.", "hangonjr"], 
["Hard Drivin' (cockpit, rev 7)", "harddriv"], 
["Hard Hat", "hardhat"], 
["Hard Head", "hardhead"], 
["Hat Trick", "hattrick"], 
["Heavy Barrel (US)", "hbarrel"], 
["Haunted Castle (version M)", "hcastle"], 
["Hyper Crash (version D)", "hcrash"], 
["Hellfire (2P set)", "hellfire"], 
["Pirate Ship Higemaru", "higemaru"], 
["Space Fever High Splitter (set 1)", "highsplt"], 
["Himeshikibu (Japan)", "himesiki"], 
["Hippodrome (US)", "hippodrm"], 
["Hit Me (set 1)", "hitme"], 
["Hit 'n Miss (version 3.0)", "hitnmiss"], 
["Hana Yayoi (Japan)", "hnayayoi"], 
["Hana Kochou (Japan, Bet)", "hnkochou"], 
["Hoccer (set 1)", "hoccer"], 
["Vs. Hogan's Alley (set HA4-1 E-1)", "hogalley"], 
["Hopping Mappy", "hopmappy"], 
["Hopper Robo", "hopprobo"], 
["Kid no Hore Hore Daisakusen", "horekid"], 
["Hot Chase", "hotchase"], 
["Hot Rod (World, 3 Players, Turbo set 1, Floppy Based)", "hotrod"], 
["Hot Shocker", "hotshock"], 
["Vs. Hot Smash", "hotsmash"], 
["House Mannequin Roppongi Live hen (Japan 870418)", "housemn2"], 
["House Mannequin (Japan 870217)", "housemnq"], 
["Video Hustler", "hustler"], 
["Heavy Metal (315-5135)", "hvymetal"], 
["Heavy Unit (World)", "hvyunit"], 
["Heavyweight Champ", "hwchamp"], 
["High Way Race", "hwrace"], 
["Hayaoshi Taisen Quiz Hyhoo (Japan)", "hyhoo"], 
["Hayaoshi Taisen Quiz Hyhoo 2 (Japan)", "hyhoo2"], 
["Hyper Sports", "hyperspt"], 
["Vs. Ice Climber (set IC4-4 B-1)", "iceclimb"], 
["Vs. Ice Climber Dual (set IC4-4 A-1)", "iceclmrd"], 
["Idol no Himitsu [BET] (Japan 890304)", "idhimitu"], 
["Idol-Mahjong Housoukyoku (Japan)", "idolmj"], 
["Indoor Soccer (set 1)", "idsoccer"], 
["Iemoto (Japan 871020)", "iemoto"], 
["New Champion Skill (v100n)", "igs_ncs"], 
["Ikari Warriors (US JAMMA)", "ikari"], 
["Ikari III - The Rescue (World, 8-Way Joystick)", "ikari3"], 
["Ikki (Japan)", "ikki"], 
["Imago (cocktail set)", "imago"], 
["Image Fight (World, revision A)", "imgfight"], 
["I'm Sorry (315-5110, US)", "imsorry"], 
["Indiana Jones and the Temple of Doom (set 1)", "indytemp"], 
["Inferno (Williams)", "inferno"], 
["Insector (prototype)", "insector"], 
["Insector X (World)", "insectx"], 
["Intrepid (set 1)", "intrepid"], 
["Space Invaders / Space Invaders M", "invaders"], 
["Ippatsu Gyakuten [BET] (Japan)", "ippatsu"], 
["I, Robot", "irobot"], 
["Iron Horse", "ironhors"], 
["Itazura Tenshi (Japan)", "itaten"], 
["Jack the Giantkiller (set 1)", "jack"], 
["Jackal (World)", "jackal"], 
["Jail Break", "jailbrek"], 
["Vs. Ninja Jajamaru Kun (Japan)", "jajamaru"], 
["Jangou [BET] (Japan)", "jangou"], 
["New Double Bet Mahjong (Japan)", "janputer"], 
["4nin-uchi Mahjong Jantotsu", "jantotsu"], 
["Jumping Cross", "jcross"], 
["Return of the Jedi", "jedi"], 
["Jin", "jin"], 
["Jitsuryoku!! Pro Yakyuu (Japan)", "jitsupro"], 
["Jumping Jack", "jjack"], 
["Jackpot Joker Poker (set 1)", "jjpoker"], 
["Jangou Lady (Japan)", "jngolady"], 
["Joinem", "joinem"], 
["Jolly Card (Austrian)", "jollycrd"], 
["Jolly Jogger", "jollyjgr"], 
["Jolly Joker (98bet, set 1)", "jolyjokr"], 
["Mahjong Block Jongbou (Japan)", "jongbou"], 
["Journey", "journey"], 
["Joust (White/Green label)", "joust"], 
["Joust 2 - Survival of the Fittest", "joust2"], 
["Joyful Road (Japan)", "joyfulr"], 
["Jr. Pac-Man", "jrpacman"], 
["Jump Bug", "jumpbug"], 
["Jump Coaster", "jumpcoas"], 
["Jump Shot", "jumpshot"], 
["Jungle King (Japan)", "junglek"], 
["Jungler", "jungler"], 
["Juno First", "junofrst"], 
["Kabuki-Z (World)", "kabukiz"], 
["Kageki (US)", "kageki"], 
["Mahjong Kaguyahime [BET] (Japan 880521)", "kaguya"], 
["Mahjong Kaguyahime Sono2 [BET] (Japan 890829)", "kaguya2"], 
["Kaitei Takara Sagashi", "kaitei"], 
["Kamikaze Cabbie", "kamikcab"], 
["Kanatsuen no Onna [BET] (Japan 880905)", "kanatuen"], 
["Kangaroo", "kangaroo"], 
["Kaos", "kaos"], 
["Karnov (US)", "karnov"], 
["Ninja Kazan (World)", "kazan"], 
["Karate Champ (US)", "kchamp"], 
["Kick (upright)", "kick"], 
["Kick Boy", "kickboy"], 
["Kicker", "kicker"], 
["Kick and Run (World)", "kicknrun"], 
["Kick Off (Japan)", "kickoff"], 
["Kick Rider", "kickridr"], 
["Meikyu Jima (Japan)", "kikcubic"], 
["KiKi KaiKai", "kikikai"], 
["Kick Start Wheelie King", "kikstart"], 
["Killer Comet", "killcom"], 
["King & Balloon (US)", "kingball"], 
["King of Boxer (English)", "kingofb"], 
["Kingpin", "kingpin"], 
["Kitten Kaboodle", "kittenk"], 
["Klax (set 1)", "klax"], 
["Knuckle Joe (set 1)", "kncljoe"], 
["Konami GT", "konamigt"], 
["Mahjong-zukino Korinai Menmen (Japan 880425)", "korinai"], 
["Kram (set 1)", "kram"], 
["Kozmik Kroozr", "kroozr"], 
["Krull", "krull"], 
["Kusayakyuu", "ksayakyu"], 
["Kung-Fu Master", "kungfum"], 
["Kung-Fu Roushi", "kungfur"], 
["Kung-Fu Taikun (set 1)", "kungfut"], 
["Kuri Kinton (World)", "kurikint"], 
["Kyros", "kyros"], 
["Last Striker / Kyuukyoku no Striker", "kyustrkr"], 
["Lady Bug", "ladybug"], 
["Lady Liner", "ladylinr"], 
["Lady Master of Kung Fu", "ladymstr"], 
["Lasso", "lasso"], 
["Last Duel (US New Ver.)", "lastduel"], 
["Last Mission (US revision 6)", "lastmisn"], 
["Last Survivor (Japan, FD1094 317-0083)", "lastsurv"], 
["Lazer Command", "lazercmd"], 
["Lode Runner (set 1)", "ldrun"], 
["Lode Runner II - The Bungeling Strikes Back", "ldrun2"], 
["Lode Runner III - The Golden Labyrinth", "ldrun3"], 
["Lode Runner IV - Teikoku Karano Dasshutsu", "ldrun4"], 
["Legend", "legend"], 
["Legion - Spinner-87 (World ver 2.03)", "legion"], 
["Leprechaun", "leprechn"], 
["Levers", "levers"], 
["Liberation", "liberate"], 
["Liberator (set 1)", "liberatr"], 
["Libble Rabble", "liblrabl"], 
["Live Gal (Japan 870530)", "livegal"], 
["Lizard Wizard", "lizwiz"], 
["The Legend of Kage", "lkage"], 
["Lunar Lander (rev 2)", "llander"], 
["Lock'n'Chase", "lnc"], 
["Lock-On (rev. E)", "lockon"], 
["Loco-Motion", "locomotn"], 
["Line of Fire / Bakudan Yarou (World, FD1094 317-0136)", "loffire"], 
["Legend of Hero Tonma", "loht"], 
["Legend of Makai (World)", "lomakai"], 
["Lost Tomb (easy)", "losttomb"], 
["Lot Lot", "lotlot"], 
["Lotto Fun", "lottofun"], 
["Lover Boy", "loverboy"], 
["Lucky 74 (bootleg, set 1)", "lucky74"], 
["New Lucky 8 Lines (set 1, W-4)", "lucky8"], 
["Lovely Cards", "lvcards"], 
["Legendary Wings (US set 1)", "lwings"], 
["Mission 660 (US)", "m660"], 
["M.A.C.H. 3", "mach3"], 
["Monoshiri Quiz Osyaberi Macha (Japan)", "macha"], 
["Macho Mouse", "machomou"], 
["Mad Alien", "madalien"], 
["Mad Crasher", "madcrash"], 
["Mad Gear (US)", "madgear"], 
["Mad Motor", "madmotor"], 
["Magic Fly", "magicfly"], 
["Mag Max", "magmax"], 
["The Main Event (4 Players ver. Y)", "mainevt"], 
["Mainline Double Joker Poker", "mainline"], 
["Main Event (1984)", "mainsnk"], 
["Mahjong Studio 101 [BET] (Japan)", "majs101b"], 
["Makaijan [BET] (Japan)", "makaijan"], 
["Mania Challenge (set 1)", "maniach"], 
["Mappy (US)", "mappy"], 
["Marble Madness (set 1)", "marble"], 
["Marine Boy", "marineb"], 
["Mario Bros. (US, Revision F)", "mario"], 
["Markham", "markham"], 
["Mars", "mars"], 
["Marvin's Maze", "marvins"], 
["Marvel Land (US)", "marvland"], 
["Master of Weapon (World)", "masterw"], 
["Match It", "matchit"], 
["Mat Mania", "matmania"], 
["Maverik", "maverik"], 
["Maxi-Dealer", "maxideal"], 
["Max RPM (ver 2)", "maxrpm"], 
["Mayday (set 1)", "mayday"], 
["Mayhem 2002", "mayhem"], 
["Kikiippatsu Mayumi-chan (Japan)", "mayumi"], 
["Amazing Maze", "maze"], 
["Maze Invaders (prototype)", "mazeinv"], 
["Miss Mahjong Contest (Japan)", "mcontest"], 
["Mechanized Attack (World)", "mechatt"], 
["Mega Blast (World)", "megablst"], 
["Megadon", "megadon"], 
["Megatack", "megatack"], 
["Mega Zone (Konami set 1)", "megazone"], 
["Meijinsen", "meijinsn"], 
["Merlins Money Maze", "merlinmm"], 
["Meta Fox", "metafox"], 
["Metal Clash (Japan)", "metlclsh"], 
["Metal Hawk", "metlhawk"], 
["Metro-Cross (set 1)", "metrocrs"], 
["Astro Chase (Max-A-Flex)", "mf_achas"], 
["Boulder Dash (Max-A-Flex)", "mf_bdash"], 
["Bristles (Max-A-Flex)", "mf_brist"], 
["Flip & Flop (Max-A-Flex)", "mf_flip"], 
["Mahjong Fun Club - Idol Saizensen (Japan)", "mfunclub"], 
["Mahjong Gakuen", "mgakuen"], 
["Mahjong Gakuen 2 Gakuen-chou no Fukushuu", "mgakuen2"], 
["Gionbana [BET] (Japan 890207)", "mgion"], 
["Mahjong G-MEN'89 (Japan 890425)", "mgmen89"], 
["Major Havoc (rev 3)", "mhavoc"], 
["Mahjong Hourouki Gaiden (Japan)", "mhgaiden"], 
["M.I.A. - Missing in Action (version T)", "mia"], 
["Midnight Resistance (World)", "midres"], 
["Vs. Mighty Bomb Jack (Japan)", "mightybj"], 
["Mikie", "mikie"], 
["Millipede", "milliped"], 
["Mighty Monkey", "mimonkey"], 
["Minefield", "minefld"], 
["Mini Golf (set 1)", "minigolf"], 
["Mirax (set 1)", "mirax"], 
["Mirai Ninja (Japan)", "mirninja"], 
["Missile Command (rev 3)", "missile"], 
["Almond Pinky [BET] (Japan)", "mjapinky"], 
["Mahjong Camera Kozou (set 1) (Japan 881109)", "mjcamera"], 
["Mahjong Camera Kozou (set 2) (Japan 881109)", "mjcamerb"], 
["Mahjong Clinic (Japan)", "mjclinic"], 
["Mahjong Shinkirou Deja Vu (Japan)", "mjdejavu"], 
["Mahjong Derringer (Japan)", "mjderngr"], 
["Mahjong Diplomat [BET] (Japan)", "mjdiplob"], 
["Mahjong Focus (Japan 890313)", "mjfocus"], 
["Mahjong Friday (Japan)", "mjfriday"], 
["Mahjong Gaiden [BET] (Japan 870803)", "mjgaiden"], 
["Mahjong Hourouki Okite (Japan)", "mjhokite"], 
["Mahjong Kojinkyouju (Private Teacher) (Japan)", "mjkojink"], 
["Major League", "mjleague"], 
["Mahjong Nanpa Story (Japan 890713)", "mjnanpas"], 
["Mahjong Natsu Monogatari (Japan)", "mjnatsu"], 
["Mahjong Shikaku (Japan 880908)", "mjsikaku"], 
["Mahjong Sisters (Japan)", "mjsister"], 
["Mahjong-yougo no Kisotairyoku (Japan)", "mjyougo"], 
["Marchen Maze (Japan)", "mmaze"], 
["Minky Monkey", "mmonkey"], 
["Mutant Night", "mnight"], 
["Maze of Flott (Japan)", "mofflott"], 
["Mole Attack", "mole"], 
["Momoko 120%", "momoko"], 
["Monte Carlo", "montecar"], 
["Moon Cresta (Nichibutsu)", "mooncrst"], 
["Moon Quasar", "moonqsr"], 
["Moonwar", "moonwar"], 
["Moon War (prototype on Frenzy hardware)", "moonwarp"], 
["Motos", "motos"], 
["Mouser", "mouser"], 
["Moon Patrol", "mpatrol"], 
["Mad Planets", "mplanets"], 
["Mr. Do!", "mrdo"], 
["The Amazing Adventures of Mr. F. Lea", "mrflea"], 
["Mr. Goemon (Japan)", "mrgoemon"], 
["Mr. Jong (Japan)", "mrjong"], 
["Mr. Kougar", "mrkougar"], 
["Mr. TNT", "mrtnt"], 
["Mister Viking (315-5041)", "mrviking"], 
["Moon Shuttle (US? set 1)", "mshuttle"], 
["Mahjong Satsujin Jiken (Japan 881017)", "msjiken"], 
["Ms. Pac-Man", "mspacman"], 
["Mouse Trap (version 5)", "mtrap"], 
["Mustache Boy", "mustache"], 
["MVP (set 2, US, FD1094 317-0143)", "mvp"], 
["MX5000", "mx5000"], 
["My Hero (US, not encrypted)", "myhero"], 
["Mystic Marathon", "mysticm"], 
["Mysterious Stones - Dr. John's Adventure", "mystston"], 
["Name That Tune (set 1)", "nametune"], 
["Narc (rev 7.00)", "narc"], 
["Nastar (World)", "nastar"], 
["NATO Defense", "natodef"], 
["Naughty Boy", "naughtyb"], 
["Nemesis (ROM version)", "nemesis"], 
["Net Wars", "netwars"], 
["New Sinbad 7", "newsin7"], 
["Nibbler (rev 9)", "nibbler"], 
["Ninja-Kid II / NinjaKun Ashura no Shou (set 1)", "ninjakd2"], 
["Ninjakun Majou no Bouken", "ninjakun"], 
["The Ninja Warriors (World)", "ninjaw"], 
["Naughty Mouse (set 1)", "nmouse"], 
["Noboranka (Japan)", "nob"], 
["Noraut Deluxe Poker (console)", "norautdx"], 
["Noraut Joker Poker (original)", "norautjo"], 
["Noraut Poker", "norautp"], 
["Noraut Joker Poker (Prologic HW)", "norautpl"], 
["Noraut Red Hot Joker Poker (alt HW)", "norautra"], 
["Noraut Red Hot Joker Poker", "norautrh"], 
["Nova 2001 (Japan)", "nova2001"], 
["Novo Play Multi Card / Club Card", "novoplay"], 
["New Lucky 8 Lines / New Super 8 Lines (W-4)", "ns8lines"], 
["New Lucky 8 Lines / New Super 8 Lines (F-5, Witch Bonus)", "ns8linew"], 
["Ninja Spirit", "nspirit"], 
["Night Stocker (10/6/86)", "nstocker"], 
["Ironman Ivan Stewart's Super Off-Road", "offroad"], 
["Ironman Ivan Stewart's Super Off-Road Track-Pak", "offroadt"], 
["Ojanko Yakata 2bankan (Japan)", "ojanko2"], 
["Ojanko Club (Japan)", "ojankoc"], 
["Ojanko High School (Japan)", "ojankohs"], 
["Ojanko Yakata (Japan)", "ojankoy"], 
["Ojousan (Japan 871204)", "ojousan"], 
["Omega Fighter", "omegaf"], 
["Omega Race (set 1)", "omegrace"], 
["Omotesandou (Japan 890215)", "omotesnd"], 
["Opa Opa (MC-8123, 317-0042)", "opaopa"], 
["Orbit", "orbit"], 
["Orbitron", "orbitron"], 
["Ordyne (Japan, English Version)", "ordyne"], 
["Psycho-Nics Oscar (World revision 0)", "oscar"], 
["Operation Thunderbolt (World)", "othunder"], 
["Otona no Mahjong (Japan 880628)", "otonano"], 
["Off the Wall (Sente)", "otwalls"], 
["Out Run (sitdown/upright, Rev B)", "outrun"], 
["Ozma Wars (set 1)", "ozmawars"], 
["Ozon I", "ozon1"], 
["P-47 - The Phantom Fighter (World)", "p47"], 
["Pac-Land (World)", "pacland"], 
["Pac-Mania", "pacmania"], 
["Pac & Pal", "pacnpal"], 
["Pac-Man Plus", "pacplus"], 
["Paddle Mania", "paddlema"], 
["Pairs (Nichibutsu) (Japan 890822)", "pairsnb"], 
["Pandora's Palace", "pandoras"], 
["Pang (World)", "pang"], 
["Paperboy (rev 3)", "paperboy"], 
["Passing Shot (World, 2 Players, FD1094 317-0080)", "passsht"], 
["Pastel Gal (Japan 851224)", "pastelg"], 
["Pinball Action (set 1)", "pbaction"], 
["Pioneer Balloon", "pballoon"], 
["Prebillian", "pbillian"], 
["Perfect Billiard", "pbillrd"], 
["Baseball (PlayChoice-10)", "pc_bball"], 
["Balloon Fight (PlayChoice-10)", "pc_bfght"], 
["Contra (PlayChoice-10)", "pc_cntra"], 
["Captain Sky Hawk (PlayChoice-10)", "pc_cshwk"], 
["Castlevania (PlayChoice-10)", "pc_cvnia"], 
["Double Dribble (PlayChoice-10)", "pc_dbldr"], 
["Double Dragon (PlayChoice-10)", "pc_ddrgn"], 
["Duck Hunt (PlayChoice-10)", "pc_duckh"], 
["Excite Bike (PlayChoice-10)", "pc_ebike"], 
["Uncle Fester's Quest: The Addams Family (PlayChoice-10)", "pc_ftqst"], 
["Golf (PlayChoice-10)", "pc_golf"], 
["The Goonies (PlayChoice-10)", "pc_goons"], 
["Gradius (PlayChoice-10)", "pc_grdus"], 
["Hogan's Alley (PlayChoice-10)", "pc_hgaly"], 
["Kung Fu (PlayChoice-10)", "pc_kngfu"], 
["Mario Bros. (PlayChoice-10)", "pc_mario"], 
["Metroid (PlayChoice-10)", "pc_mtoid"], 
["Ninja Gaiden (PlayChoice-10)", "pc_ngaid"], 
["Pro Wrestling (PlayChoice-10)", "pc_pwrst"], 
["Rad Racer (PlayChoice-10)", "pc_radrc"], 
["R.C. Pro-Am (PlayChoice-10)", "pc_rcpam"], 
["Rush'n Attack (PlayChoice-10)", "pc_rnatk"], 
["Chip'n Dale: Rescue Rangers (PlayChoice-10)", "pc_rrngr"], 
["Rygar (PlayChoice-10)", "pc_rygar"], 
["Super Mario Bros. (PlayChoice-10)", "pc_smb"], 
["Super Mario Bros. 2 (PlayChoice-10)", "pc_smb2"], 
["Super Mario Bros. 3 (PlayChoice-10)", "pc_smb3"], 
["Tecmo Bowl (PlayChoice-10)", "pc_tbowl"], 
["Tennis (PlayChoice-10)", "pc_tenis"], 
["Track & Field (PlayChoice-10)", "pc_tkfld"], 
["Teenage Mutant Ninja Turtles (PlayChoice-10)", "pc_tmnt"], 
["Trojan (PlayChoice-10)", "pc_trjan"], 
["Volley Ball (PlayChoice-10)", "pc_vball"], 
["Wild Gunman (PlayChoice-10)", "pc_wgnmn"], 
["Pocket Gal (Japan)", "pcktgal"], 
["Power Drift (World, Rev A)", "pdrift"], 
["Penguin Adventure (bootleg of MSX version)", "pengadvb"], 
["Pengo (set 1 rev c)", "pengo"], 
["Player's Edge Plus (PP0043) 10's or Better", "pepp0043"], 
["Player's Edge Plus (PP0065) Jokers Wild Poker", "pepp0065"], 
["Player's Edge Plus (PP0158) 4 of a Kind Bonus Poker", "pepp0158"], 
["Player's Edge Plus (PP0188) Standard Draw Poker", "pepp0188"], 
["Player's Edge Plus (PP0250) Double Down Stud Poker", "pepp0250"], 
["Player's Edge Plus (PP0447) Standard Draw Poker", "pepp0447"], 
["Player's Edge Plus (PP0516) Double Bonus Poker", "pepp0516"], 
["Pepper II (version 8)", "pepper2"], 
["The Percussor", "percuss"], 
["Performan (Japan)", "perfrman"], 
["Pesadelo (bootleg of Knightmare on MSX)", "pesadelo"], 
["Player's Edge Plus (Set038) Set Chip", "peset038"], 
["Peter Pack-Rat", "peterpak"], 
["Phelios (Japan)", "phelios"], 
["Phoenix (Amstar)", "phoenix"], 
["Phozon (Japan)", "phozon"], 
["Phraze Craze (set 1)", "phrcraze"], 
["Pickin'", "pickin"], 
["Pinbo (set 1)", "pinbo"], 
["Konami's Ping-Pong", "pingpong"], 
["Pirate Treasure", "piratetr"], 
["Pitfall II (315-5093)", "pitfall2"], 
["Poker Ladies", "pkladies"], 
["Penguin-Kun Wars (US)", "pkunwar"], 
["Vs. Platoon", "platoon"], 
["PlayBall! (prototype)", "playball"], 
["Plotting (World set 1)", "plotting"], 
["Plump Pop (Japan)", "plumppop"], 
["Plus Alpha", "plusalph"], 
["PlayMan Poker (German)", "pmpoker"], 
["Poker 4-1", "poker41"], 
["Polaris (Latest version)", "polaris"], 
["Pole Position", "polepos"], 
["Pole Position II", "polepos2"], 
["Poly-Play", "polyplay"], 
["Pong (Rev E)", "pong"], 
["Pong (Rev E), no subcycles", "pongf"], 
["Ponpoko", "ponpoko"], 
["Pontoon (Tehkan)", "ponttehk"], 
["Poolshark", "poolshrk"], 
["Pooyan", "pooyan"], 
["Popeye (revision D)", "popeye"], 
["Pop Flamer (protected)", "popflame"], 
["Porky", "porky"], 
["Jack Potten's Poker (set 1)", "pottnpkr"], 
["P.O.W. - Prisoners of War (US version 1)", "pow"], 
["Power Drive", "powerdrv"], 
["Power Play", "powrplay"], 
["Prehistoric Isle in 1930 (World)", "prehisle"], 
["Professor Pac-Man", "profpac"], 
["Progress", "progress"], 
["Progressive Music Trivia (Question set 1)", "promutrv"], 
["Pro Soccer", "prosoccr"], 
["Tennis (bootleg of Pro Tennis)", "protennb"], 
["Power Surge", "psurge"], 
["Psychic 5 (set 1)", "psychic5"], 
["Psycho Soldier (US)", "psychos"], 
["PuckMan (Japan set 1)", "puckman"], 
["Pull Tabs", "pulltabs"], 
["Punch-Out!!", "punchout"], 
["Puzznic (World)", "puzznic"], 
["Qix (Rev 2)", "qix"], 
["Quantum (rev 2)", "quantum"], 
["Quarterback (set 1)", "quarterb"], 
["Quester (Japan)", "quester"], 
["Quiz Olympic (set 1)", "quizo"], 
["Qwak (prototype)", "qwak"], 
["R2D Tank", "r2dtank"], 
["Rabio Lepus (Japan)", "rabiolep"], 
["Racing Hero (FD1094 317-0144)", "rachero"], 
["Rack 'em Up (program code L)", "rackemup"], 
["Rack + Roll", "racknrol"], 
["Radar Scope", "radarscp"], 
["Radical Radial", "radrad"], 
["Rafflesia (315-5162)", "raflesia"], 
["Raiders5", "raiders5"], 
["Raimais (World)", "raimais"], 
["Rally Bike / Dash Yarou", "rallybik"], 
["Rambo III (Europe)", "rambo3"], 
["Rampage (ver 3 8-27-86)", "rampage"], 
["Rastan (World Rev 1)", "rastan"], 
["Vs. Atari R.B.I. Baseball (set 1)", "rbibb"], 
["Rainbow Islands (new version)", "rbisland"], 
["Reaktor (Track & Field conversion)", "reaktor"], 
["Recordbreaker (World)", "recordbr"], 
["Red Baron (Revised Hardware)", "redbaron"], 
["Redline Racer (2 players)", "redlin2p"], 
["Red Robin", "redrobin"], 
["Defend the Terra Attack on the Red UFO", "redufo"], 
["Regulus (315-5033, Rev A.)", "regulus"], 
["Reikai Doushi (Japan)", "reikaids"], 
["Renegade (US)", "renegade"], 
["Repulse", "repulse"], 
["Rescue Raider (5/11/87) (non-cartridge)", "rescraid"], 
["Rescue", "rescue"], 
["Return of the Invaders", "retofinv"], 
["Riddle of Pythagoras (Japan)", "ridleofp"], 
["Roller Jammer", "rjammer"], 
["Real Mahjong Haihai (Japan)", "rmhaihai"], 
["Real Mahjong Haihai Jinji Idou Hen (Japan)", "rmhaijin"], 
["Real Mahjong Haihai Seichouhen (Japan)", "rmhaisei"], 
["Road Blasters (upright, rev 4)", "roadblst"], 
["Road Fighter (set 1)", "roadf"], 
["Road Runner (rev 2)", "roadrunn"], 
["Robby Roto", "robby"], 
["Robocop (World revision 4)", "robocop"], 
["Atomic Robo-kid", "robokid"], 
["Robotron: 2084 (Solid Blue label)", "robotron"], 
["Robo Wres 2001", "robowres"], 
["Rock Climber", "rockclim"], 
["Rock'n Rage (World)", "rockrage"], 
["MTV Rock-N-Roll Trivia (Part 2)", "rocktrv2"], 
["Roc'n Rope", "rocnrope"], 
["The Return of Ishtar", "roishtar"], 
["Rompers (Japan)", "rompers"], 
["Round-Up", "roundup"], 
["Route 16 (set 1)", "route16"], 
["Royal Mahjong (Japan, v1.13)", "royalmj"], 
["Royal Card (Nichibutsu)", "roylcrdn"], 
["River Patrol (Orca)", "rpatrol"], 
["Rolling Thunder (new version)", "rthunder"], 
["R-Type (World)", "rtype"], 
["R-Type II", "rtype2"], 
["Runaway (prototype)", "runaway"], 
["Rygar (US set 1)", "rygar"], 
["Salamander (version D)", "salamand"], 
["Sarge", "sarge"], 
["Saturn", "saturnzi"], 
["Sauro", "sauro"], 
["Super Bagman", "sbagman"], 
["Super Basketball (version I, encrypted)", "sbasketb"], 
["Super Breakout (rev 04)", "sbrkout"], 
["Scandal Mahjong (Japan 890213)", "scandal"], 
["Super Cobra", "scobra"], 
["Super Contra", "scontra"], 
["Scooter Shooter", "scotrsht"], 
["Scramble", "scramble"], 
["Scrambled Egg", "scregg"], 
["Screw Loose (prototype)", "screwloo"], 
["SDI - Strategic Defense Initiative (Japan, old, System 16A, FD1089B 317-0027)", "sdi"], 
["Super Doubles Tennis", "sdtennis"], 
["Space Dungeon", "sdungeon"], 
["SAR - Search And Rescue (World)", "searchar"], 
["Second Love (Japan 861201)", "secolove"], 
["Second Chance", "secondch"], 
["Section Z (set 1)", "sectionz"], 
["Sega Ninja (315-5102)", "seganinj"], 
["Seicross", "seicross"], 
["Seiha (Japan 870725)", "seiha"], 
["Senjyo", "senjyo"], 
["Sente Diagnostic Cartridge", "sentetst"], 
["Sex Triv", "sextriv"], 
["Street Fighter (World, Analog buttons)", "sf"], 
["Super Free Kick (set 1)", "sfkick"], 
["Street Football (11/12/86)", "sfootbal"], 
["Sea Fighter Poseidon", "sfposeid"], 
["SF-X", "sfx"], 
["Gladiator 1984", "sgladiat"], 
["Shackled (US)", "shackled"], 
["Shadowland", "shadowld"], 
["Shadow Warriors (World, set 1)", "shadoww"], 
["Shanghai II (Japan)", "shangha2"], 
["Shanghai Kid", "shangkid"], 
["Super Hang-On (sitdown/upright, unprotected)", "shangon"], 
["Shark Attack", "sharkatt"], 
["Space Harrier (Rev A, 8751 315-5163A)", "sharrier"], 
["Shadow Dancer (World)", "shdancer"], 
["Sheriff", "sheriff"], 
["Shinobi (set 6, System 16A, unprotected)", "shinobi"], 
["Satan's Hollow (set 1)", "shollow"], 
["Shoot the Bull", "shootbul"], 
["Shoot Out (US)", "shootout"], 
["Shougi", "shougi"], 
["Showdown (version 5.0)", "showdown"], 
["Shrike Avenger (prototype)", "shrike"], 
["Shot Rider", "shtrider"], 
["Super Invader Attack", "sia2650"], 
["Side Pocket (World)", "sidepckt"], 
["Silk Worm (World)", "silkworm"], 
["Silver Game", "silverga"], 
["Sindbad Mystery", "sindbadm"], 
["Sinistar (revision 3)", "sinistar"], 
["Sukeban Jansi Ryuko (set 2, System 16B, FD1089B 317-5021)", "sjryuko"], 
["Skull & Crossbones (rev 5)", "skullxbo"], 
["Sky Adventure (World)", "skyadvnt"], 
["Sky Army", "skyarmy"], 
["Sky Base", "skybase"], 
["Sky Diver", "skydiver"], 
["Sky Fox", "skyfox"], 
["Sky Kid (new version)", "skykid"], 
["Sky Kid Deluxe (set 1)", "skykiddx"], 
["Sky Lancer", "skylancr"], 
["Sky Skipper", "skyskipr"], 
["Sky Soldiers (US)", "skysoldr"], 
["Slither (set 1)", "slither"], 
["Sly Spy (US revision 3)", "slyspy"], 
["Vs. Stroke & Match Golf (Men Version, set GF4-2 F)", "smgolf"], 
["Super Monaco GP (World, Rev B, FD1094 317-0126a)", "smgp"], 
["Snake Pit", "snakepit"], 
["Snacks'n Jaxson", "snakjack"], 
["Snap Jack", "snapjack"], 
["Atari Soccer", "soccer"], 
["Solar Fox (upright)", "solarfox"], 
["Solomon's Key (US)", "solomon"], 
["Sonic Boom (FD1094 317-0053)", "sonicbom"], 
["Son Son", "sonson"], 
["Super Othello", "sothello"], 
["Space Duel", "spacduel"], 
["Space Cruiser", "spacecr"], 
["Space Fever (New Ver.)", "spacefev"], 
["Space Launcher", "spacelnc"], 
["Space Seeker", "spaceskr"], 
["Space Zap", "spacezap"], 
["Spatter", "spatter"], 
["Space Position (Japan)", "spcpostn"], 
["Speed Ball (prototype)", "spdball"], 
["Speed Coin (prototype)", "spdcoin"], 
["Super Dodge Ball (US)", "spdodgeb"], 
["Speak & Rescue", "speakres"], 
["Speed Attack! (Japan)", "speedatk"], 
["Speed Ball", "speedbal"], 
["Spelunker", "spelunkr"], 
["Spiker", "spiker"], 
["Splat!", "splat"], 
["Splatter House (World new version)", "splatter"], 
["Super Punch-Out!!", "spnchout"], 
["Super Cross II (Japan, set 1)", "sprcros2"], 
["Springer", "springer"], 
["Sprint 1", "sprint1"], 
["Sprint 4 (set 1)", "sprint4"], 
["Sprint 8", "sprint8"], 
["S.P.Y. - Special Project Y (World ver. N)", "spy"], 
["Spy Hunter", "spyhunt"], 
["Spy Hunter 2 (rev 2)", "spyhunt2"], 
["Super Qix (World, Rev 2)", "sqix"], 
["Squash (Itisa)", "squaitsa"], 
["Space Raider", "sraider"], 
["Super Ranger (v2.0)", "sranger"], 
["Super Real Darwin (World)", "srdarwin"], 
["S.R.D. Mission", "srdmissn"], 
["Super Real Mahjong Part 1 (Japan)", "srmp1"], 
["Super Real Mahjong Part 2 (Japan)", "srmp2"], 
["Super Real Mahjong Part 3 (Japan)", "srmp3"], 
["The Speed Rumbler (set 1)", "srumbler"], 
["SSI Poker (v2.4)", "ssipkr24"], 
["Syusse Oozumou (Japan)", "ssozumo"], 
["Scramble Spirits (World, Floppy Based)", "sspirits"], 
["Super Sprint (rev 4)", "ssprint"], 
["Stadium Hero (Japan)", "stadhero"], 
["Star Force", "starforc"], 
["Stargate", "stargate"], 
["Star Guards", "stargrds"], 
["Star Jacker (Sega)", "starjack"], 
["Vs. Star Luster", "starlstr"], 
["Star Wars (rev 2)", "starwars"], 
["Triv Two", "statriv2"], 
["Triv Four", "statriv4"], 
["Status Black Jack (V1.0c)", "statusbj"], 
["Saint Dragon (set 1)", "stdragon"], 
["Stocker (3/19/85)", "stocker"], 
["Stompin' (4/4/86)", "stompin"], 
["Strategy X", "stratgyx"], 
["Street Smart (US version 2)", "streetsm"], 
["Strider (USA, B-Board 89624B-2)", "strider"], 
["Strike Zone Baseball", "strkzone"], 
["Strength & Skill", "strnskil"], 
["Street Heat", "strtheat"], 
["S.T.U.N. Runner (rev 6)", "stunrun"], 
["Submarine", "sub"], 
["Super Casino", "sucasino"], 
["Super Draw Poker (set 1)", "supdrapo"], 
["Super Twenty One", "super21"], 
["Super Bug", "superbug"], 
["Superman (World)", "superman"], 
["Super Pac-Man", "superpac"], 
["Super Tank", "supertnk"], 
["Super Triv II", "supertr2"], 
["Super Triv III", "supertr3"], 
["Super Glob", "suprglob"], 
["Super League (FD1094 317-0045)", "suprleag"], 
["Super Locomotive", "suprloco"], 
["Super Mouse", "suprmous"], 
["Vs. Super Mario Bros. (set SM4-4 E)", "suprmrio"], 
["Vs. Super Xevious", "supxevs"], 
["Sure Shot", "sureshot"], 
["Watashiha Suzumechan (Japan)", "suzume"], 
["Super Volleyball (Japan)", "svolley"], 
["SWAT (315-5048)", "swat"], 
["Swimmer (set 1)", "swimmer"], 
["Syvalion (Japan)", "syvalion"], 
["Tactician (set 1)", "tactcian"], 
["Tail to Nose - Great Championship", "tail2nos"], 
["Taiwan Mahjong [BET] (Japan 881208)", "taiwanmb"], 
["Talbot", "talbot"], 
["Tank 8 (set 1)", "tank8"], 
["Tank Busters", "tankbust"], 
["Tapper (Budweiser, set 1)", "tapper"], 
["Tazz-Mania (set 1)", "tazmania"], 
["Tecmo Bowl (World)", "tbowl"], 
["Thunder Ceptor", "tceptor"], 
["TouchDown Fever (US)", "tdfever"], 
["Triple Draw Poker", "tdpgal"], 
["John Elway's Team Quarterback (set 1)", "teamqb"], 
["TeddyBoy Blues (315-5115, New Ver.)", "teddybb"], 
["Tee'd Off (Japan)", "teedoff"], 
["Teeter Torture (prototype)", "teetert"], 
["Tehkan World Cup (set 1)", "tehkanwc"], 
["Telephone Mahjong (Japan 890111)", "telmahjn"], 
["Tempest (rev 3, Revised Hardware)", "tempest"], 
["Ten Up (compendium 17)", "tenup"], 
["Terra Cresta (YM3526 set 1)", "terracre"], 
["Terra Force", "terraf"], 
["Tetris (set 4, Japan, System 16A, FD1094 317-0093)", "tetris"], 
["Tetris (Japan, System E)", "tetrisse"], 
["The Deep (Japan)", "thedeep"], 
["The End", "theend"], 
["The Mah-jong (Japan)", "themj"], 
["The Pit", "thepit"], 
["Thief", "thief"], 
["Thunder Blade (upright, FD1094 317-0056)", "thndrbld"], 
["Thunder Cross (set 1)", "thunderx"], 
["Tic Tac Trivia (Horizontal)", "tictac"], 
["Tiger Heli (US)", "tigerh"], 
["Tiger Road (US)", "tigeroad"], 
["Timber", "timber"], 
["Time Pilot", "timeplt"], 
["Time Scanner (set 2, System 16B)", "timescan"], 
["Time Soldiers (US Rev 3)", "timesold"], 
["Time Tunnel", "timetunl"], 
["The Tin Star (set 1)", "tinstar"], 
["Vs. T.K.O. Boxing", "tkoboxng"], 
["Teenage Mutant Ninja Turtles (World 4 Players)", "tmnt"], 
["Thundercade / Twin Formation", "tndrcade"], 
["The Next Space", "tnextspc"], 
["T.N.K III (US)", "tnk3"], 
["The NewZealand Story (World, new version) (newer PCB)", "tnzs"], 
["The Tower of Druaga (New Ver.)", "todruaga"], 
["Tougenkyou (Japan 890418)", "togenkyo"], 
["Toggle (prototype)", "toggle"], 
["Toki (World, set 1)", "toki"], 
["Toki no Senshi - Chrono Soldier", "tokisens"], 
["Tokyo Gal Zukan (Japan)", "tokyogal"], 
["TomCat (prototype)", "tomcat"], 
["Tonton [BET] (Japan set 1)", "tontonb"], 
["Toobin' (rev 3)", "toobin"], 
["Vs. Top Gun", "topgun"], 
["Top Gunner (Exidy)", "topgunnr"], 
["Top Secret (Exidy) (version 1.0)", "topsecex"], 
["Tournament Table (set 1)", "tourtabl"], 
["Turbo Out Run (Out Run upgrade, FD1094 317-0118)", "toutrun"], 
["Toypop", "toypop"], 
["Time Pilot '84 (set 1)", "tp84"], 
["Track & Field", "trackfld"], 
["Transformer", "transfrm"], 
["Traverse USA / Zippy Race", "travrusa"], 
["Tricky Doc (set 1)", "trckydoc"], 
["Trick Trap (World?)", "tricktrp"], 
["Trio The Punch - Never Forget Me... (World)", "triothep"], 
["Triple Punch", "triplep"], 
["Mahjong Triple Wars (Japan)", "triplew1"], 
["Triple Hunt", "triplhnt"], 
["Tri-Pool (Casino Tech)", "tripool"], 
["Tri-Sports", "trisport"], 
["Trivial Pursuit (Baby Boomer Edition) (3/20/85)", "triviabb"], 
["Trivial Pursuit (Spanish)", "triviaes"], 
["Trivial Pursuit (Think Tank - Genus Edition) (set 1)", "triviag1"], 
["Trivial Pursuit (Genus II Edition)", "triviag2"], 
["Trivial Pursuit (All Star Sports Edition)", "triviasp"], 
["Trivial Pursuit (Young Players Edition)", "triviayp"], 
["Triv Quiz", "trivquiz"], 
["Tropical Angel", "troangel"], 
["Trojan (US set 1)", "trojan"], 
["Tron (8/9)", "tron"], 
["Truco-Tron", "truco"], 
["Truxton / Tatsujin", "truxton"], 
["Trivia Hangup (question set 1)", "trvhang"], 
["Trivia Master (set 1)", "trvmstr"], 
["Trivia Quest", "trvquest"], 
["Trivia ? Whiz (Edition 2) (question set 1)", "trvwz2"], 
["Trivia ? Whiz (Edition 3 - Horizontal) (set 1)", "trvwz3h"], 
["Trivia ? Whiz (Edition 4) (question set 1)", "trvwz4"], 
["Trivia ? Whiz (Horizontal) (question set 1)", "trvwzh"], 
["Pro Baseball Skill Tryout (Japan)", "tryout"], 
["Samurai Nihon-Ichi (set 1)", "tsamurai"], 
["Shingen Samurai-Fighter (Japan, English)", "tshingen"], 
["Turkey Shoot", "tshoot"], 
["T.T Mahjong", "ttmahjng"], 
["Tube Panic", "tubep"], 
["Tunnel Hunt", "tunhunt"], 
["Turbo Sub (prototype rev. TSCA)", "turbosub"], 
["Turbo Tag (prototype)", "turbotag"], 
["Turtles", "turtles"], 
["Turtle Ship (North America)", "turtship"], 
["TwinBee (ROM version)", "twinbee"], 
["Twin Cobra (World)", "twincobr"], 
["Twin Eagle - Revenge Joe's Brother", "twineagl"], 
["Twin Falcons", "twinfalc"], 
["Twin Hawk (World)", "twinhawk"], 
["Mahjong Uchuu yori Ai wo komete (Japan)", "uchuuai"], 
["Ufo Senshi Yohko Chan (MC-8123, 317-0064)", "ufosensi"], 
["Ultra Tank", "ultratnk"], 
["Uncle Poo", "unclepoo"], 
["UniWar S", "uniwars"], 
["U.N. Squadron (USA)", "unsquad"], 
["Untouchable (Japan)", "untoucha"], 
["Up'n Down (315-5030)", "upndown"], 
["Up Your Alley", "upyoural"], 
["U.S. Classic", "usclssic"], 
["Games V18.2", "usg182"], 
["Super Duper Casino (California V3.2)", "usg32"], 
["Super Ten V8.3", "usg83"], 
["Us vs. Them", "usvsthem"], 
["Valkyrie No Densetsu (Japan)", "valkyrie"], 
["Vanguard II", "vangrd2"], 
["Van-Van Car", "vanvan"], 
["Vapor Trail - Hyper Offence Formation (World revision 1)", "vaportra"], 
["Vastar (set 1)", "vastar"], 
["U.S. Championship V'ball (US)", "vball"], 
["Vega", "vega"], 
["Venture (version 5 set 1)", "venture"], 
["Victory", "victory"], 
["Victory Road", "victroad"], 
["Video Pinball", "videopin"], 
["Video Poker", "videopkr"], 
["Vigilante (World, set 1)", "vigilant"], 
["Vindicators Part II (rev 3)", "vindctr2"], 
["Vindicators (rev 5)", "vindictr"], 
["Violence Fight (World)", "viofight"], 
["Viper", "viper"], 
["Mahjong Vitamin C (Japan)", "vitaminc"], 
["Volfied (World, revision 1)", "volfied"], 
["Vs. BaseBall (US, set BA E-1)", "vsbball"], 
["Vs. Freedom Force", "vsfdf"], 
["Vs. Gradius", "vsgradus"], 
["Vs. Gumshoe (set GM5)", "vsgshoe"], 
["Vs. Mahjong (Japan)", "vsmahjng"], 
["Vs. Pinball (set ?)", "vspinbal"], 
["Vs. Super SkyKid", "vsskykid"], 
["Vs. Soccer (set SC4-2 A)", "vssoccer"], 
["Vs. Tennis (Japan/USA, set TE A-3)", "vstennis"], 
["Vs. Tetris", "vstetris"], 
["Vulcan Venture (New)", "vulcan"], 
["Vulgus (set 1)", "vulgus"], 
["Wacko", "wacko"], 
["Wall Crash (set 1)", "wallc"], 
["Wanted", "wanted"], 
["Wardner (World)", "wardner"], 
["Warlords", "warlords"], 
["War of the Bugs or Monsterous Manouvers in a Mushroom Maze", "warofbug"], 
["Warp & Warp", "warpwarp"], 
["Water Ski", "waterski"], 
["Wonder Boy III - Monster Lair (set 5, World, System 16B, 8751 317-0098)", "wb3"], 
["Wonder Boy in Monster Land (Japan New Ver., MC-8123, 317-0043)", "wbml"], 
["Wonder Boy (set 1, 315-5177)", "wboy"], 
["WEC Le Mans 24", "wecleman"], 
["Wheel Of Fortune (set 1)", "wfortune"], 
["Who Dunit (version 8.0)", "whodunit"], 
["Wild Fang / Tecmo Knight", "wildfang"], 
["Willow (USA)", "willow"], 
["Wily Tower", "wilytowr"], 
["Winners Circle (82)", "winner82"], 
["Wiping", "wiping"], 
["Wit's (Japan)", "wits"], 
["Wiz", "wiz"], 
["Wiz Warz (prototype)", "wizwarz"], 
["Wizz Quiz (Konami version)", "wizzquiz"], 
["World Court (Japan)", "wldcourt"], 
["Water Match (315-5064)", "wmatch"], 
["Wonder Planet (Japan)", "wndrplnt"], 
["Woodpecker (set 1)", "woodpeck"], 
["World Wars (World?)", "worldwar"], 
["Vs. Wrecking Crew", "wrecking"], 
["Wrestle War (set 3, World, 8751 317-0103)", "wrestwar"], 
["World Stadium (Japan)", "ws"], 
["World Series: The Season", "wseries"], 
["World Tennis", "wtennis"], 
["Wild Western (set 1)", "wwestern"], 
["WWF Superstars (Europe)", "wwfsstar"], 
["Wai Wai Jockey Gate-In!", "wwjgtin"], 
["Xenophobe", "xenophob"], 
["Xevious (Namco)", "xevious"], 
["X Multiply (World, M81)", "xmultipl"], 
["Xain'd Sleena", "xsleena"], 
["XX Mission", "xxmissio"], 
["Xybots (rev 2)", "xybots"], 
["Xyonix", "xyonix"], 
["Yie Ar Kung-Fu (program code I)", "yiear"], 
["Youjyuden (Japan)", "youjyudn"], 
["Yukon (version 2.0)", "yukon"], 
["Zaviga", "zaviga"], 
["Zero Wing (1P set)", "zerowing"], 
["Zig Zag (Galaxian hardware, set 1)", "zigzag"], 
["Zoar", "zoar"], 
["Zoo Keeper (set 1)", "zookeep"], 
["Zwackery", "zwackery"], 
["Zzyzzyxx (set 1)", "zzyzzyxx"]]

def log(v):
    xbmc.log(re.sub(',',',\n',repr(v)))

@plugin.route('/default')
def default():
    snaps = plugin.get_setting('snaps')
    titles = plugin.get_setting('titles')
    cabinets = plugin.get_setting('cabinets')
    marquees = plugin.get_setting('marquees')
    flyers = plugin.get_setting('flyers')
    items = [
        {'label': r[0], 
        'thumbnail': '%s%s.png' % (snaps,r[1]), 
        'icon': '%s%s.png' % (marquees,r[1]), 
        'path': plugin.url_for('play', rom=r[1]),
        'properties' : {
        'fanart_image' : '%s%s.png' % (flyers,r[1]), 
        'banner' : '%s%s.png' % (marquees,r[1]), 
        'clearlogo': '%s%s.png' % (titles,r[1]), 
        'poster': '%s%s.png' % (cabinets,r[1]), 
        }
        } for r in games
    ]
    plugin.set_content('movies')
    sorted_items = sorted(items, key=lambda item: item['label'])
    return sorted_items

#@plugin.route('/filter', name='filter_options', options={'clone': 'false', 'year_start' : '0', 'year_end' : '9999', 'name' : '', 'players' : '', 'manufacturer': '', 'rom' : ''})
#def filter(clone, year_start, year_end, name, players, manufacturer, rom):
#@plugin.route('/filter', name='filter_options', options={'clone': 'false'})
@plugin.route('/filter/<clone>/<start>/<end>/<name>/<rom>')
def filter(clone,start,end,name,rom):
    #xbmc.log(clone)
    #xbmc.log(start)
    #xbmc.log(end)
    exe = plugin.get_setting('exe')
    (path,mame) = os.path.split(exe)
    with open(os.path.join(path,'mame.json'), 'r') as infile:
        list = json.load(infile)
    
    log(len(list))

    #sorted_games = sorted(games, key=lambda game: game[1])    
    
    keepers = []
    for l in list:
        keep = True
        if l['cloneof']:
            label = "[COLOR orange]%s[/COLOR] - [COLOR green]%s[/COLOR] - %s [B]%s[/B]" % (l['description'], l['year'], l['name'], l['cloneof'],  )
        else:
            label = "[COLOR yellow][B]%s[/B][/COLOR] - [COLOR green]%s[/COLOR] - %s [B]%s[/B]" % (l['description'], l['year'], l['name'], l['cloneof'],  )
        if l['cloneof'] != "" and clone == 'false':
            keep = False
        
        #year = int(re.sub('\?','0',l['year']))
        year = l['year']
        if '?' in year:
            year = -1
        else:
            year = int(year)
        #log(year)
        if year < int(start) or year > int(end):
            keep = False
        
        if name != '?':
            #log(name)
            if not re.search(name, l['description'],re.I):
                keep = False
                
        if rom != '?':
            #log(name)
            if not re.search(rom, l['name'],re.I):
                keep = False
        '''
        if players:
            if int(l['players']) != players:
                keep = False
        if manufacturer:
            if not re.search(manufacturer, l['manufacturer']):
                keep = False
        if rom:
            if not re.search(rom, l['rom']):
                keep = False
        '''
        if keep:
            l['label'] = label
            keepers.append(l)
            #games.append((label, l['name']))
    log(len(keepers))
    out_keepers = []
    for l in keepers:
        if l['cloneof'] == '':
            l['cloneof'] = l['name']
            l['name'] = ''
        out_keepers.append(l)
    #log(out_keepers)
    log(len(out_keepers))
    sorted_list = sorted(out_keepers, key = lambda x: (x['cloneof'], x['name']))
    #log(sorted_list)
    
    games = []
    for l in sorted_list:
        games.append((l['label'], l['name']))
    
    #sorted_games = sorted(games, key=lambda game: game[1])                

    snaps = plugin.get_setting('snaps')
    titles = plugin.get_setting('titles')
    cabinets = plugin.get_setting('cabinets')
    marquees = plugin.get_setting('marquees')
    flyers = plugin.get_setting('flyers')
    items = [
        {'label': r[0], 
        'thumbnail': '%s%s.png' % (snaps,r[1]), 
        'icon': '%s%s.png' % (marquees,r[1]), 
        'path': plugin.url_for('play', rom=r[1]),
        'properties' : {
        'fanart_image' : '%s%s.png' % (flyers,r[1]), 
        'banner' : '%s%s.png' % (marquees,r[1]), 
        'clearlogo': '%s%s.png' % (titles,r[1]), 
        'poster': '%s%s.png' % (cabinets,r[1]), 
        }
        } for r in games
    ]
    plugin.set_content('movies')
    #sorted_items = sorted(items, key=lambda item: item['label'])
    return items

@plugin.route('/')
def index():

    items = [
    {
        'label': "All",
        'path': plugin.url_for('filter' , clone='true', start='-2', end='9999', name='?', rom='?'),

    } ,    
    
    {
        'label': "No Clones",
        'path': plugin.url_for('filter', clone='false', start='-2', end='9999', name='?', rom='?'),

    } ,
    {
        'label': "Clones",
        'path': plugin.url_for('filter', clone='true', start='-2', end='9999', name='?', rom='?'),

    },
    {
        'label': "Invaders",
        'path': plugin.url_for('filter', clone='false', start='-2', end='9999', name='invaders', rom='?'),

    }, 
    {
        'label': "inv rom",
        'path': plugin.url_for('filter', clone='true', start='-2', end='9999', name='?', rom='inv'),

    },     {
        'label': "Golden",
        'path': plugin.url_for('filter', clone='false', start='1977', end='1982', name='?', rom='?'),

    },
        {
        'label': "1980",
        'path': plugin.url_for('filter', clone='true', start='1980', end='1980', name='?', rom='?'),

    },
    {
        'label': "Pre 1980",
        'path': plugin.url_for('filter', clone='true', start='0', end='1979', name='?', rom='?'),

    },
    {
        'label': "Unknown Year",
        'path': plugin.url_for('filter', clone='false', start='-2', end='0', name='?', rom='?'),

    },    ]

    sorted_items = sorted(items, key=lambda item: item['label'])
    return sorted_items

@plugin.route('/play/<rom>/')
def play(rom):
    exe = plugin.get_setting('exe')
    roms = plugin.get_setting('roms')
    # Normally we would use label to parse a specific web page, in this case we are just
    # using it for a new list item label to show how URL parsing works.
    items = [
        {'label': rom},
    ]
    #subprocess.call(["c:\emulators\mame\mame.exe", "amidar"])
    #subprocess.Popen(['mame', 'amidar'], cwd='c:\\emulators\\mame')
    #return items
    #from subprocess import Popen, PIPE, STDOUT
    #handle = Popen(['mame.exe', 'amidar' ], shell=True, stdout=PIPE, stderr=STDOUT, stdin=PIPE, cwd=r'C:\emulators\mame')
    (path,mame) = os.path.split(exe)
    handle = Popen([exe, rom, '-rompath', roms], shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, stdin=subprocess.PIPE,cwd=path)
    xbmc.log(handle.stdout.readline().strip())
    
if __name__ == '__main__':
    plugin.run()
